### ISSUE TITLE
Death Beacons that don't clear

### ISSUE THREAD

**Issue by xienwolf** [Kikiisyourfriend/damage_inc#2]
When you die, there is a waypoint generated by Journeymap with a random color. But also a white beacon light.

Clearing the Journeymap waypoint does NOT clear the white beacon, those seem to stay eternally.

**Comment by Kikiisyourfriend** [comment]
Those can be cleared. My pack has two map mods. Journeymap and FTBChunks. If you press M it'll open up FTB's map and you can hit the cogwheel and disable those beacons. Hope this helps you and thank you for testing out the pack!
