### ISSUE TITLE
Steel Available early

### ISSUE THREAD

**Issue by xienwolf** [Kikiisyourfriend/damage_inc#3]
The progression quests lead me to believe that Steel is meant to be obtained using the Alloy Smelter.  But you can just put Iron in a Smelter or furnace and change the output from refined iron to steel.

Not a major issue really, The early access didn't give much benefit, I think I was able to make nicer glass was about all.

**Comment by Kikiisyourfriend** [comment]
Alloy smelter yes. Mainly to get your solar power going iirc. Also when you say furnace I'm assuming you mean blast furnace then yes; that one is intentional as well.

**Comment by Kikiisyourfriend** [comment]
Oh and they are also used to get you your first solar power. Forgot to mention that
