### ISSUE TITLE
FTB Chunk Loading breaks fluids

### ISSUE THREAD

**Issue by xienwolf** [Kikiisyourfriend/damage_inc#4]
If I claim a chunk and then set it to force load, I am no longer able to use buckets to place or pick up water/lava.

When placing, it appears to empty the bucket, but the fluid instantly disappears. If you pick up the bucket in inventory it shows the fluid still inside.

When trying to pick up, the fluid disappears, no new fluid flows into the space, and the bucket appears to hold the fluid, but the bucket interacts with other things like it is empty.

Unclaim the chunk and everything works fine again.

**Comment by Kikiisyourfriend** [comment]
Indeed. We are currently having this issue as well. Will comb through the mod again to see if anything was added client side to configure but it seems it's an FTBChunks issue atm.

**Comment by Kikiisyourfriend** [comment]
This issue has been fixed by FTB! Yay!
