### ISSUE TITLE
Wither doesn't drop Stars?

### ISSUE THREAD

**Issue by xienwolf** [Kikiisyourfriend/damage_inc#5]
Killed the wither twice now. Both times, no drops at all.

Are we meant to only get nether stars with the 2 dragon egg + wither components recipe?  Would be good to add a mention in the quests or tooltip on nether stars.

**Comment by Kikiisyourfriend** [comment]
Indeed they do drop with kills. We've killed many. What version of the pack are you playing?

**Comment by xienwolf** [comment]
0.2.2

I am trapping the wither in a standard suffocation cube, and killing it with Lycanite weaponry.  Not sure if either of those are impacting things.  Also in the overworld, and down near bedrock level.

**Comment by Kikiisyourfriend** [comment]
Not sure about the lycanite weapon but I know the suffocating method does not work with progressive bosses iirc.
Need to pretty much kill it the legit way or perhaps a mob killer from industrial foregoing.
(I need to try the crusher myself)
Try also using a silent or tinker weapon and let me know if you do.

**Comment by xienwolf** [comment]
It may have been that the final hit came from suffocation damage.  I wasn't able to do much damage on those first 2 attempts.  I have killed it twice more using a Tinker weapon these times and got drops as expected.

**Comment by Kikiisyourfriend** [comment]
Aye. The Mob Crusher also does work for stars as well.
