### ISSUE TITLE
Un-crafting balance

### ISSUE THREAD

**Issue by xienwolf** [Kikiisyourfriend/damage_inc#6]
Salvager is good. It only pulls apart standard armor/tools.  Seems to pay attention to the damage on them as well.

But the cyclic Uncrafting Grinder is a problem. It can take apart essentially everything, which allows you uncraft the Soul Cube and get an Ultimate Casing, which you can then uncraft to get most of the gateway machine parts.

The only "hard" part to get for the uncrafting grinder is the Crystallized Obsidian, which needs a chorus fruit.  Normally that gates it to The End, so no problem.  But you can get Chorus fruit from Banshees and a few other Overworld available Lycanite mobs.  It is quite possible to get the whole thing without even going to the Nether, though finding a Soul Cube prior to nether relies completely on luck with treasure chests. Once you get to the Nether, they seem plentiful though.

**Comment by Kikiisyourfriend** [comment]
Good find! I will have to gate this item.
