### ISSUE TITLE
No multiplayer possible

### ISSUE THREAD

**Issue by grigoreme** [Kikiisyourfriend/damage_inc#7]
As the title says, no multiplayer is possible.

I figured out that it's related to flat bedrock and after I removed it and cleared the config and saved the world it started to work.

How I made it work:

1. Create a new server with the same forge version
2. Copy mods&config
3. Remove camoucreeper-2.0.0 ( or similar ) and `ScalingHealth-1.16.5-4.1.5+11`
4. Start the server.

Repeat the process with the client and only then it works.

**Comment by Kikiisyourfriend** [comment]
There are client side mods that conflict with putting my pack on a server. I still have yet to figure out how to make server files for packs. I do apologize.
