### ISSUE TITLE
Botania prodcution flower freeze if no spreader

### ISSUE THREAD

**Issue by xienwolf** [Kikiisyourfriend/damage_inc#8]
Pretty sure I finally figured out the cause on this one.  I was adding some mana generation to my base and when I put down an endoflame the game totally locked up.  Had to force re-start.  Would only happen if I placed flowers in a certain area of the base.

I noticed later on that none of the flowers I placed when I locked up were bound to mana spreaders.  And I think that was the cause of the lock up.

**Comment by Kikiisyourfriend** [comment]
I wish I was able to figure this one out. It has happened to us as well and I did completely forget to add it to the Known Issues.
